### ISSUE TITLE
Expand current user profile with Reservation

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-profile#132]
### Tasks
__SBL Bridge__
- [x] Update SblBridge mapping logic to set the new reservation flag.
- [x] QA
- [x] Manual test

__Altinn Platform models__
- [x] Update profile model to include reservation property
- [x] QA

__Altinn Profile__
- [x] Update Altinn Profile to map all new values between SBL user profile and platform models user profile 
- [x] Implement caching of user profile
- [x] QA
- [x] Manual test: at23
- [x] Automated tests

## Acceptance criteria 

- [x] User profile is retrieved from cache whenever cache is available instead of calling SBL
- [x] User profile endpoint used by Altinn Apps expose the reservation flag

**Comment by acn-sbuad** [comment]
verified with apps-test in at23
