### ISSUE TITLE
Implement endpoints for exposing address points and reservation info in Altinn Profile

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-profile#136]
## Description
Altinn Notifications needs information about the contact points for a given user and information about their reservations. 

Two endpoints should be implemented, a lightweight endpoint only informing that a contact point exists and whether or not the user is reserved, and another endpoint to expose the actual data. 

```json
"nationalIdentityNumber": "1234568"
"isReserved": false
"emailRegistered": true
"mobileRegistered": true
```

```json
"nationalIdentityNumber": "1234568",
"email": "test@test.com",
"mobileNumber": "12345678",
"isReserved": false
```

## Consideration

- [x] Where should the new models be implemented?  
  - In Profile, no need to implement them in the Platform Models project. 

## Tasks
- [x] Implement new internal endpoint, decorator and service for exposing only address point & reservation for a user. Should re-use the cached userprofile where applicable
- [x] Implement new internal endpoint for availability of contact points for end user. Should re-use cached user profile where applicable
- [x] QA
- [x] Manual test

## Acceptance criteria
- [ ] New endpoints are not exposed through APIM
- [ ] Endpoint exists for retrieving address points for an end user based of national identity number
- [ ] Endpoint exists for retrieving information of availability of contact points for an end user 
- [ ] Both endpoints can accept a list of national identity number and return the requested data.

**Comment by acn-sbuad** [comment]
Endpoint cannot be verified outside of the cluser. Will be verified along with a different issue
