### ISSUE TITLE
Identify and configure necessary accesses for Profile using Workload identity

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-profile#141]
### Description
The Profile application should be updated to access azure resources through workload identity.

#### Identified resources:
- [ ] Read access to Platform KeyVault

### Tasks
- [x] Configure the necessary accesses through workload identity (helm chart)
    - [x] Service account
    - [x] Azure AD configuration?
- [x] Update the code to no longer use the kvSettings to access the KeyVault
- [ ] QA
- [ ] Manual tests

### Acceptance criteria
- [ ] Profile can access the platform key vault without the explicitly shared credentials.

```[tasklist]
### Tasks
- [x] at21
- [x] at22
- [x] at23
- [x] at24
- [x] yt01
- [x] tt02
- [x] prod
```
