### ISSUE TITLE
Document profile data, ui elements and data usage

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-profile#163]
### Description
Create a detailed overview of profile data, user interfaces and how the data is being used.

### Tasks
- [ ] Identify and document data stored in Altinn 2
  - [ ] Document connected UI elements in Altinn 2
  - [ ] Document business logic using the data
- [ ] Review

### Acceptance criteria
- [ ] Finished document
