### ISSUE TITLE
Establish KRR integration

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-profile#187]
### Description

Add necessary logic for the synchronization with KRR. Use the same mechanisms as we have in Altinn 2. Request the change log from KRR and re-play the changes as they appear into our own database.

Link to KRR doc: https://docs.digdir.no/docs/Kontaktregisteret/oppslagstjenesten_rest.html 

The client code for KRR should be in in the Integration project of the Profile solution. 

### Additional info
The code for the batch program running in Altinn 2:
(private link) https://dev.azure.com/digdir/_git/Altinn?path=/SBL/Batch/ContactReservationRegisterSync

The Altinn 2 batch framework is multi threaded with one batch producer and multiple batch consumers. If the batch program used for KRR is using multiple consumers we need to consider copying more of the batch framework.

The initial code is in the ExecuteBlock method and it looks like it is called only once (one consumer). The method performs calls to a service in Register(SBL) which performs the work.

### Tasks

- [x] https://github.com/Altinn/altinn-profile/issues/195
- [x] Configure KRR credentials
- [ ] Feature/job: initial  dataload
- [x] Feature: incremental/delta-updates
- [x] Update values in helm charts
    - [x] Admin DB Connection string (Using CNAME)
    - [x] DB Connection string (Using CNAME)
    - [x] EnableDBConnection (toggle)
- [x] Add secrets for Maskinporten to KeyVaults (ClientId and EncodedJwk)
    - [x] AT21 - SKIPPED
    - [x] AT22
    - [x] AT23
    - [x] AT24
    - [x] YT01
    - [x] TT02
    - [x] Prod

To be decided: what to do if the full/delta difrentiation is not as easy as just starting at 0 and incrementing a counter.

### Acceptance criteria:
- [ ] Our code can call the KRR API and get a sucessfull response back (i.e. with data)

**Comment by olebhansen** [comment]
FYI, the relevant code to take inspiration from is (in Altinn2) Altinn.SBL.Register / CRR / CRRClientWrapper, and the common credentials-manager "HttpClientUsingMaskinporten" (which in turn uses "Altinn.Common.Util.MaskinPortenUtil"). 

I can help with the actual credentials.

**Comment by Ahmed-Ghanam** [comment]
The functionality has been implemented in the feature branch `feature/187-establish-krr-integration`. To meet our team's standards, the unit test coverage must be increased to pass the defined threshold. For more details, please refer to this pull request: [Add an endpoint to synchronize the KKR database with updates from the change log](https://github.com/Altinn/altinn-profile/pull/221)

**Comment by Ahmed-Ghanam** [comment]
@SandGrainOne Took over this task can decide what to do next.
