### ISSUE TITLE
OVV - Create integration-code to fetch data from remote 

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-profile#202]
### Description
This task is to code the API-calls to BR/OVV to fetch data (i.e. read-only / one-way-synch FROM BR/OVV).
Part of this task should be to "solve" how to do incremental and batched updates. This will require research into the availbale OVV system API.

Regular triggering of this integration for the purpose of keeping our replica in synch, is in task #206

Client code should be a part of the profile integrations project.

Future support for write-operations will be part of #201 

Be aware of possible IP filtering at BR.

### Additional information
Altinn 2 batch: (private repo) https://dev.azure.com/digdir/_git/Altinn?path=/SBL/Batch/KoFuVi/KoFuViSync.cs

Documentation: https://www.brreg.no/teknisk-beskrivelse/kofuvi/#introduksjon

### Considerations
Add propper support for CancelationToken in the call chain involving sync job.

### Tasks
- [ ] https://github.com/Altinn/altinn-profile/issues/205
- [ ] Configure OVV credentials. Enterprise certificate
- [ ] Feature: incremental/delta-updates
    - Analyse the batch in Altinn 2 and associated logic in the Register component.
    - Implement the same logic in Profile.
    - The job should be triggered with a HTTPS call against a new endpoint in TriggerController.

**To be decided**: What to do if the full/delta difrentiation is not as easy as just starting at 0 and incrementing a counter.
**Decided**: We assume that we can start from 0, but it should be investigated.

### Acceptance criteria:
- [ ] Our code can call the OVV API and get a sucessfull response back (i.e. with data)

### Things to discuss
- **Threat modelling**
Discuss possible security issues
- **Documentation**
- [x] Do we need to update documentation in altinn docs?
- [x] Do we need Internal documentation (confluence)?
- **External tests**
- [ ] Should new functionality be Regression tested?
- [ ] Should new functionality be included in Usecase tests?
- **Acceptance criteria**
Does the issue have defined acceptance criteria?
