### ISSUE TITLE
OVV - Establish DB schema

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-profile#204]
### Description
See #186 and its list of improvements to see it any of the items from KRR is relevant/applicable for the OVV schema. 

The approach should be "code first". Use "unique index" rather than constraints. Use EF to generate sql scripts if possible. Adapt them for yuniql migration.

### Additional information
The tables in Altinn 2 are all in a schema called KoFuVi in the Register database. We can copy the definitions from there.

Remember that Entity Framework is the way forward, so stored procedures would likely be replaced by EF-features.

### Tasks
- [ ] Define a schema: organization_contact_info 
- [ ] Create tables and indexes
- [ ] Include the batch status table for metadata for the sync job.

### Acceptance criteria:
- [ ] OVV Schema deployed to the DB, ready to recieve data and queries.

**Comment by sigridbra** [comment]
New schema name 
_organization_notification_address_

Tables:
_organizations
notification_addresses_

**Comment by SandGrainOne** [comment]
**Test:**
I basically just checked the server in AT23 for any changes and everything looks like it's in order with the changes here.
