### ISSUE TITLE
OVV - Create Read-API for notifications

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-profile#207]
### Description
The data in Altinn 2 is currently made available through the Register component. In this issue we will implement a new  endpoint with the same data in Profile.

This API will be backwards compatible with the current needs of notification. There will be other endpoints to retrieve data on a format more suitable for other uses like the new GUI defined by "arbeidsflate".

Suggested API endpoint:
POST /profile/api/v1/organizations/contactpoint/lookup

### Tasks
- [ ] Create a controller to have endpoints for doing "OVV" lookup.
- [ ] Define the external request and respons models inspired by the models in register
- [ ] Implement the necessary call chain between the Controller and database to support the lookup.

### Acceptance criteria
- [ ] The OVV data for an org. can be retrieved on a new endpoint.

**Comment by sigridbra** [comment]
@SandGrainOne Do we need a change in APIM, to test this? Or do we just do test from notifications API? I have tested this through notificationsAPI locally only.  If I understand correctly we should not open in APIM as the resource is not publicly available.

**Comment by sigridbra** [comment]
Tested with port forwarding to AT22:
* Lookup of 1 orgNumber ✔ 
* Lookup of multiple orgNumbers ✔ 
* Lookup of not existing orgNumber ✔ 
* Lookup of empty string ✔ 
* Lookup of multiple orgNumbers where some are found ✔ 
* Lookup of the same orgNumber multiple times in the lookup list ✔
