### ISSUE TITLE
Update existing UserContactPoint endpoints to get data from KRR copy

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-profile#220]
### Description

The existing UserContactPoint endpoints needs to be updated to provide data from the local copy of KRR instead of retrieving data from Altinn 2. The new logic should be conditional behind a "feature flag"

POST profile/api/v1/users/contactpoint/lookup
POST profile/api/v1/users/contactpoint/availability

### Tasks

- [x] Introduce a boolean setting to turn local data retrieval on or off. Default is off/false.
- [x] Add logic and necessary mapping of models to use local KRR copy when the feature is turned on.
- [x] Investigate the consequence of not having a UserId for the return values
- [x] Delete both `PersonContactDetailsController` and `PersonContactDetailsInternalController` 

### Acceptance Criterias

- [x] When feature flag is off, data is retrieved from Altinn 2
- [x] When feature flag is on, data is retrieved from Altinn 3 copy of KRR.

**Comment by NathalieFroissart** [comment]
@Ahmed-Ghanam update descriptions regarding controllers

**Comment by Ahmed-Ghanam** [comment]
The `PersonContactDetailsController` and `PersonContactDetailsInternalController` each include an endpoint designed to retrieve data from the database. Check the call chain to understand their usage in data retrieval and subsequently remove these controllers after updating the existing endpoint.
