### ISSUE TITLE
Maskinporten settings secrets needs to be added to the KeyVault with terraform

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-profile#229]
### Description

I've currently added the necessary secrets directly to the KeyVault. This should be changed so that the KeyVault is populated with terraform instead.

It's the two secrets:
- ContactAndReservationSettings--Maskinporten--ClientId
- ContactAndReservationSettings--Maskinporten--EncodedJwk

There should be one pair for test and one pair for prod. The test pair is usable in all environments except in production where the production pair is used.

### Additional Information

Notifications have an identical setup for the MaskinportenSettings used by the send condition client.

### Tasks

- [x] Add test and production secrets to the terraform secrets-source KeyVault with appropriate names
- [x] Update terraform scripts to read the secrets and to have them uploaded to the environment specific platform keyvaults

For every env, tag must be added ([like in AT22](https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/commit/53e1654764818e03f34913e29a2c79a5dfa36a08?refName=refs/heads/master)), existing secrets deleted in KV, pipeline run with TF apply, and KV verified post-deployment

  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] TT02
  - [x] YT
  - [x] Prod

### Acceptance Criterias

- [x] Running platform deploy creates/updates the secrets in platform key vault with the values from the terraform key vault.

**Comment by hggutvik** [comment]
Working on it here, https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/1139
