### ISSUE TITLE
Turn off the received-first-response traces

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-profile#262]
### Description

NOTE: This change requires a new version of the Npgsql package(s).

The default tracing from NpgSQL includes traces with the message received-first-response. There is a lot of them and we probably don't have any need for them. 

Update nuget packages and turn off `EnableFirstResponseEvent`.

### Additional Information

They're adding new options to the `NpgsqlTracingOptions` class. The one that is interesting for us is the `EnableFirstResponseEvent` property.
https://github.com/npgsql/npgsql/pull/5853/files#diff-e3555b1bea8f96895a00eff9a7462125d6224cd6fb1601be8d1562abf306f7aa

### Tasks

- [ ] Bump nuget packages with the necessary changes
- [ ] Set EnableFirstResponseEvent to false

### Acceptance Criteria

- [ ] There are no received-first-response traces any longer

**Comment by SandGrainOne** [comment]
@hggutvik Is this issue redundant now?

**Comment by hggutvik** [comment]
@SandGrainOne Yes - only Notifications still has this issue
