### ISSUE TITLE
Replace deprecated Microsoft.Azure.* packages

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-profile#45]
### Description

Microsoft.Azure.Services.AppAuthentication is deprecated. Package should be replaces by [Azure.Identity](https://www.nuget.org/packages/Azure.Identity).

Microsoft.Azure.KeyVault is deprected. Package should be replace by Azure.Security.KeyVault

Ref: https://azure.github.io/azure-sdk/releases/deprecated/index.html#net

### Tasks
- [x] Change implementation to use new dependencies
- [x] QA
- [x] Test

### Acceptance Criterias

- [x] Profile backend project no longer references the deprecated package
- [x] Regression tests are successful
- [x] Component still logs to application insights
