### ISSUE TITLE
Adding GUID to UserProfile

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-profile#94]
### Description

Today, a UserProfile has an int32 primary that is used for ID, which anyone can easily iterate over.
In Altinn 2 a new unique ID has been added to the authentication userprofile: UserUUID
This will be used for identifying the recipient when navigating from Altinn 2 to Altinn 3 UI when delegating rights to the user.

The update input and lookup for the internal API endpoint for lookup of UserProfile:
`POST profile/api/v1/internal/user`

### Additional Information

Delegating rights to users will be possible with
- UserUUID or SSN + last name

But this will be handled by access-management

### Tasks

- [ ] Update existing model, mapping and APIs
- [ ] Update Internal lookup API (incl. new SBL Bridge Client operation)
- [x] Deploy nuget package update for Altinn.Platform.Models for the update

### Acceptance Criteria

It is possible to identify a user without needing to have ssn/lastname, and it is not guessable.
